### PR TITLE
__update__ for PySide2 support for nuke11 and  added "from nukescripts import"

### PR DESCRIPTION
**Pull request by tws0002**

### CODE REVIEW

**Comment by eoyilmaz** [comment]
Don't use ``from nukescripts import *`` it will contaminate the main namespace use ``import nukescripts``.

**Comment by tws0002** [comment]
ok I will make the change

**Comment by tws0002** [comment]
but i having this error !! if not using from `nukescripts import *`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File \anima\anima\ui\scripts\nuke.py", line 28, in version_creator
    set_qt_lib()
  File "\anima\anima\ui\scripts\nuke.py", line 12, in set_qt_lib
    if nuke.NUKE_VERSION_MAJOR < 10 or (nuke.NUKE_VERSION_MAJOR == 11):
AttributeError: 'module' object has no attribute 'NUKE_VERSION_MAJOR'
```

**Comment by eoyilmaz** [comment]
You should do:

```python
import nukescripts
nukescripts.NUKE_VERSION_MAJOR  # instead of nuke.NUKE_VERSION_MAJOR
                                # nuke belongs to anima,
                                # what you should use is nukescript
```

**Comment by tws0002** [comment]
here is the error from nuke scripts editor 
```
import nukescripts
nukescripts.NUKE_VERSION_MAJOR
```
Result 
```
import nukescripts
nukescripts.NUKE_VERSION_MAJOR
# Result: Traceback (most recent call last):
  File "<string>", line 2, in <module>
AttributeError: 'module' object has no attribute 'NUKE_VERSION_MAJOR'
```

**Comment by tws0002** [comment]
Hi, what do u think about this error?

**Comment by eoyilmaz** [comment]
I've added ``anima`` to Nuke for a very old version of Nuke (something like version 6 or 7) so it may not work with the latest Nuke versions.

But it seems a bug which is relatively easy to fix. Just find the new way of getting the current Nuke version through the ``nukescripts`` module.

**Comment by predat** [comment]
There are several constants in the nuke:
nuke.NUKE_VERSION_MAJOR
nuke.NUKE_VERSION_MINOR
nuke.NUKE_VERSION_DATE
nuke.NUKE_VERSION_PHASE
nuke.NUKE_VERSION_PHASENUMBER
nuke.NUKE_VERSION_RELEASE
nuke.NUKE_VERSION_STRING

**Pull request merged**
